### PR TITLE
Add solar PV app for people who divert excess generation

### PR DESCRIPTION
**Pull request by mattjgalloway**
This pull request adds a new app for solar PV users who have an immersion diverter such as the Immersun or Solar iBoost.

The idea is that you can track how much of your solar is going to actually power the house and how much is powering the immersion.

There's likely still some work to be done, but I wanted to get this PR in so that people can point out where I might need to change things to be in the emonCMS style.

Here's a screenshot of it in action:
screencapture-emoncms-galloway-me-uk-app-1472208523257

### CODE REVIEW

**Comment by mattjgalloway** [comment]
I need to add some tweaks to the history view page. I can't do it just yet as I don't have enough data (just set OEM up a couple of days ago!) to really see what's going on.

My plan is to have it show total usage split by house and immersion, like the power view.

**Comment by pb66** [comment]
Hi Matt, this is a great addition IMO. I haven't tried using it yet or looked that closely at the detail, but I would welcome this as it has always been an issue for me whether to include diverted "free" energy in "use" to see how well I was utilising the PV or exclude it to see how much I was actually consuming "on purpose" or "on demand" maybe a better term.
One minor recommendation though, would be to use a more generic term like "diverted" as many users also divert to other things like a battery system, underfloor heating or and electric car as well as an immersion heater, some even switch between two or more of those.  
I look forward to trying it out.
Paul

**Comment by mattjgalloway** [comment]
Sure! I can change the wording. I'll keep working on it.

I also think it would be good to somehow split out a lot of the handling for all these apps as they are all effectively the same thing with slightly different views. I started making this an option on the My Solar PV one, but that made the code quite complicated. But if we split out helper functions, that could work. I'll see what I can do after this is done.

**Comment by rodwilliams** [comment]
Hi Matt,

It is great that you are doing this.  I have a similar requirement, I need to show diverted power, but also need to include production from a wind as well as solar.  The combined renewables would be simpler than for the MySolar&Wind app as there will CT readings for both the solar and wind readings.

Do you think there is a straightforward way to graft this into the work you have already done?

Kind regards,

Rod

**Comment by mattjgalloway** [comment]
@rodwilliams - Hmm, that could be tricky to just bolt on. It's a little annoying that the apps are very copy & paste, but that's the way it is right now.

I *could* change the wording from "solar" to "generated" and then provide an optional second feed which gets added to the first feed to make up the "generated". That way you could add in your wind to the overall generated feed. However you wouldn't see wind and solar split out.

To make it show things split out by wind, we'd probably want Yet-Another-App. That is until the apps can be made to be more customisable without simply creating a new one.

**Comment by rodwilliams** [comment]
@mattjgalloway I'm trying to think of the simplest way to get the more complex behaviour added in.  If the optional second feed (maybe called wind) is defined then the title for the field name could change from "solar" to "generated" and the two feed values could be combined.  This could later be enhanced to show the values for the two feeds as text and to show the two contributions in the graph.  I'm not sure how this would tie into the history.

I'm new to emoncms and github but I'll have a look and see if I can contribute.

**Comment by mattjgalloway** [comment]
@rodwilliams That could work yeh. I'll have a play with that. Hmm might be pretty easy actually now I think about it.

Would you want the numbers at the bottom to be %s of total generation I assume? What I mean by that is, the numbers at the very bottom of the screen show the total solar generation (currently) and what % was used on the house, the divert and export. I guess you'd be happy for that to be the sum of solar + wind there?

**Comment by rodwilliams** [comment]
@mattjgalloway Using total generation figure sounds good.  

I thought about the display and maybe it could be better grouped.  What do you think of the following:
divertgenerateapp

**Comment by mattjgalloway** [comment]
@rodwilliams - see latest commit. It's working.

As for your suggestions on the way to lay out the data - I'm working on some tweaks there right now. I think it's a little confusing right now, and it shows, because the way you're thinking about it is different to what is displayed.

What I wanted is total use in one row, and solar generation in the second row. The left column shows the total of each row and the others show the sum of what's left. (Apart from "import" on the first row is not really part of that sum, adding to the confusion!).

This is what it looks like right now:
screencapture-emoncms-galloway-me-uk-app-1473277113431

Essentially it's:

Row 1: Total usage = house usage + diverted usage. Import % tacked on the end.
Row 2: Solar generated = solar used on house + solar used on divert (yes same number as above) + solar exported.

Of course, change solar for total in row 2 now that we have wind in there as well!

I'm going to play around with some things to make that bottom section a little easier to understand.

**Comment by mattjgalloway** [comment]
I'm going with something like this right now:

screen shot 2016-09-07 at 22 19 37

Needs a bit more styling, but I think this is more understandable. And we can split solar into solar & wind as well.

**Comment by rodwilliams** [comment]
@mattjgalloway I like it.  I think that is a more accessible way to present the information compared to the earlier footer.  

If the pull request is accepted does this app become available on emoncms.org?

**Comment by mattjgalloway** [comment]
Cool I'll continue to tweak this. I kind of want import and export to be the same box and label the arrows. Since they are both "the grid".

As for EmonCMS.org - that's for Trystan to decide I guess!

**Comment by mattjgalloway** [comment]
This is where I've got to tonight. I think this is much easier to understand. But now I want to get some percentages in there. Particularly what I care about is the % my import is of my house usage.

screen shot 2016-09-08 at 21 49 22

**Comment by glynhudson** [comment]
I like it, it's very understandable. With regard to styling in would prefer
dropping the coloured boxes in favour for a translucent wire frame keeping
the auroras. What do you think @trystanlea?

- sent from my mobile device

**Comment by mattjgalloway** [comment]
@glynhudson - Glad you like it! Do you mean a border, with a semi-transparent fill of the colour? That seems like it could be nice.

**Comment by mattjgalloway** [comment]
And added in the %s that I think are important:

screen shot 2016-09-08 at 22 33 27

I'll look into making the boxes less "in your face" tomorrow, following Glyn's suggestion.

**Comment by pb66** [comment]
Further to the [discussion on the forum](https://community.openenergymonitor.org/t/correcting-nan-in-mysolar/1525?u=pb66) 

If you are sticking with the block theme is it worth considering putting the percentages just inside the blocks eg in "solar" 2 on the bottom edge and one on the left and in "house" just inside the top edge, so that the overall size is smaller and the gaps in between the blocks marry up with the block sizes, plus driving fully home, to what the percentages belong.

Not that it isn't currently clear enough, but the %'s do seem a bit disconnected from their "of", (could be mistaken to be 28% and 21% of 0.4kWh's at first glance) and they take up a fair bit of space too.

Maybe then the grey kWhs could be black within a grey arrow shaped block rather than with an additional small arrow, reducing the "small bits" in the bold blocky theme and emphasizing the direction of flow at the same time, (if it's possible to use "inverting text colour" the larger values could be allowed to spill out of the arrow shape).

And if the "inside %ages" cause and issue for larger values in the "solar" and "grid" blocks, you could put the value above the label in those top boxes as the label size will not increase and therefore not effect the %age positioning.

Just thinking out loud and chipping in some thoughts, I really like what you are doing here.

**Comment by mattjgalloway** [comment]
> added a rough mock up of the %ages inside the blocks, what do you think?

Interesting approach. I like this direction. It certainly explains the percentages much better.

On the "use to divert" - we'd need another measurement for that right? I don't currently have that right now. Could be a nice addition though. Although I'm not sure the word "divert" is right then in that case?

I'll need to get my thinking cap on for how best to lay this out in code. Making it responsive is the hardest bit. It's tricky to get things looking good on a small mobile screen as well as a large screen. Currently I remove the "kWh" on small screens, which helps, but my concern with this approach is that the percentages will get wrapped up with the words "SOLAR" and "HOUSE".

**Comment by pb66** [comment]
> we'd need another measurement for that right?

Yes, well sort of, it depends on your setup. I just send the "on/off" signal of my manual "boost" logic/switch to emoncms as a "1" or "0" and multiply the diverted by that to accumulate the power to "diverted" or "boosted", but a separate feed is probably required, unless the app was clever enough to notice import and diversion happening together and track the overlap.

In fact,I now think that would be a good metric either way to show the efficiency of your diverting system.

> I'm not sure the word "divert" is right then in that case?

I agree, but finding the right wording is always tricky, I'm sure there is someone out there diverting wind generated power to some plant at a workshop ie both "solar" and "house" would be wrong.

I actually prefer "diverted" to "divert" though, as "divert" is an action such as "import" or "export" which I see are not used either. In this context "diverted" would be the load(s) power is diverted to, not the "amount diverted".

> Making it responsive is the hardest bit. It's tricky to get things looking good on a small mobile screen as well as a large screen.

I have no doubt! It certainly isn't something that I could tackle without a very steep learning curve beforehand (if at all) so your efforts are very appreciated and it's nice to get involved alittle even though I couldn't deliver the finished result myself.

**Comment by TrystanLea** [comment]
This looks great! nice work, shall I go ahead and merge?

**Comment by mattjgalloway** [comment]
Happy for a merge myself. Would appreciate a glance over the code to check I've not done anything silly but it is all tested my end.

WDYT about the current style of the bottom section? I like it personally and I've been using it for a while and find it intuitive now. But I'd love others to start using it and providing feedback.

I'd like to continue work on it - I wonder what's the best way for that @TrystanLea? I can keep doing PRs I guess?

**Comment by pb66** [comment]
It would be really nice to see this merged!

@mattjgalloway  - What were your thoughts on monitoring the "boosting" of the diverted load(s) by calculating it from simultaneous import and divert?

It would be a good metric to follow ie is DHW provided 100% by "free energy" or not? Without that feature wouldn't the "Divert" total always be exactly the same value as the grey/arrowed value between the Solar and Divert boxes in your last layout?

**Comment by Paul-Reed** [comment]
Looks good Matt, I've been running it for the past few days. 
I'm not a fan of the blocks, but if I merge it as it is, you will get a wider range of feedback to influence development.

Paul

**Comment by mattjgalloway** [comment]
> @mattjgalloway - What were your thoughts on monitoring the "boosting" of the diverted load(s) by calculating it from simultaneous import and divert?

Ah yes I forgot about this, apologies! I have a concern with it in that then there needs to be an arrow from GRID to DIVERT. Unless we tied that up under the GRID to HOUSE and then had a HOUSE > DIVERT arrow. But that might be confusing?

> Also, what is the plan regarding MySolar vs MySolarDivert, will all users just have both or is there away to set a "display diversion" setting so that there can be just the one MySolar app?

It's currently 2 apps. I don't particularly like it like that. When I get some time, what I'd like to do is merge them, and at the same time give the MySolarPV the new bottom section from this one. However I'd love some more input on that first, and properly nail it before using it on MySolarPV. (Assuming everyone is happy with this, that is!)

**Comment by Paul-Reed** [comment]
We need to be mindful that a number of folks are making use of old disused tablets & phones to permanently display 'My Solar' in their homes, as it has been carefully formatted to fit the screens.
I would assume that any replacement would need to meet the same criteria too?

Paul

**Comment by TrystanLea** [comment]
If the changes are only to the solarpv+divert app I dont see any reason why you cant merge those in when you see fit. Discussing via a pull request is always good too. 

Id keep the mysolarpv app as is for now and have these both separate. Perhaps once you think it can replace the mysolarpv app then it would be good for those of us running mysolarpv to test to see if there are any issues?

**Comment by mattjgalloway** [comment]
Sounds good. Yes for sure we would want to keep the current solar app around until everyone is happy with any new version.

I'll find some time in the next couple of weeks to work on making mine work without a divert feed.

**Pull request merged**
