### PR TITLE
remade the window resize event listener without jquery

### LINKED ISSUE #96: Loading 3 times on Firefox android
When scrolling on my electric (and other apps?) seem like the graphs get refreshed multiple times.

### PR DESCRIPTION
**Pull request by emrysr**
fix #96 

@danbates2 thanks for reporting this issue.

I've replaced the jquery `window.onResize()` event listener with one that doesn't use jquery... seemed to fix it?? 
https://github.com/emoncms/app/blob/master/apps/OpenEnergyMonitor/myelectric/myelectric.php#L614

not 100% sure why the issue was caused with the previous code, however I would see multiple unrequired requests for data as the screen was resized - I couldn't see the issue when scrolling.

could you let me know if this is still an issue (once pulled into master or by testing this pull request)

thanks.

### CODE REVIEW

**Comment by danbates2** [comment]
Good one Emrys,

Need reminding.. What's the git command to pull this PR onto my rPi?

Do I navigate to the apps direstory and switch branch?

**Comment by emrysr** [comment]
@danbates2 
```
git checkout -b emrysr-fix/issue-96-multiple-loading-on-resize master
git pull https://github.com/emrysr/app.git fix/issue-96-multiple-loading-on-resize
```

**Comment by danbates2** [comment]
cheers.
I'm on stable
I can't find the command line instruction section, but went to the modules folder and did those two commands. everything went screwy, could access the admin page.
database thing is it?

I did `git checkout stable` to return and everything worked again.

**Comment by emrysr** [comment]
@danbates2 - make sure you're in the `modules/apps` directory to checkout my branch of the `app` repository.

Try:
```
$ cd Modules/app
$ git checkout -b emrysr-fix/issue-96-multiple-loading-on-resize master
$ git pull https://github.com/emrysr/app.git fix/issue-96-multiple-loading-on-resize
```
Probably screwed up coz you changed `emoncms` to my `app` branch - that would screw it up!

**Comment by glynhudson** [comment]
I'm also unable to re-create this issue

**Comment by TrystanLea** [comment]
Testing here with My Electric app I can still see the graphs redrawn multiple times both with new and old implementation.

**Comment by danbates2** [comment]
@TrystanLea which Browser app are you using again Trys? Chrome or Firefox?
We saw this issue on Firefox mobile app right?

**Comment by TrystanLea** [comment]
Im testing this on my laptop using firefox, it looks like the myelectric graphs reload 4-5 times when the window size is "tablet" proportions

**Comment by emrysr** [comment]
I've now added a custom event `window.resized` to fix this issue:
```
$(document).on('window.resized', resize)
```
emoncms pull request required:
https://github.com/emoncms/emoncms/pull/1397

here is a screenshot of the original multiple loads per screen problem:
my-electric-multiple-requests-problem
(4 window resize events triggered off 37 requests for data.json)

here is a screenshot of the data only being loaded once per resize with the modified js
my-electric-multiple-requests
(7 window resize events triggered off 7 requests for data.json)

tested this on chrome and firefox on desktop.

hope this better explains the problem.... let me know if not.

**Pull request merged**
