### PR TITLE
New App - Cost Comparison

### PR DESCRIPTION
**Pull request by stuartpittaway**
Hello.  I've written a new app for providing cost comparison of energy tariffs.  Its based on the time of use app, however works down to a 30 minute interval, allows unlimited tiers of tariffs and provides break downs and graphs on usage and cost.

This also requires the P.R for emoncms to fix an issue with the split function (submitted separately).  I've emulated the blue skin theme, although can change to the darker theme if thats the way the site is going?!?

### CODE REVIEW

**Comment by TrystanLea** [comment]
Wow! nice work, that's amazing! In particular the averaged day profile over the selected period, you can really see in my case the higher night time consumption from only a relatively small number of EV charges:
 
timeofuse

@greebo on the forums is also interested in this, wish I had realised what you where working on earlier: https://community.openenergymonitor.org/t/my-electric-time-of-use-app-for-economy-10/4421/20

**Comment by stuartpittaway** [comment]
It only took a day to put together. I'm looking at the smart usage tariffs
at the moment and emoncms didn't do what I wanted!

Glad it's working first try on your test box.

Stu.

**Comment by glynhudson** [comment]
Wow, agree. This looks great and really useful

**Comment by stuartpittaway** [comment]
Great. How often does emoncms software/website update?

**Pull request merged**
