### PR TITLE
Display net battery usage when charging and discharging at the same time

### PR DESCRIPTION
**Pull request by iz4c**

### CODE REVIEW

**Comment by jernaug** [comment]
Good change.. the fact you can be discharging at 1kW yet the mysolarpvbattery app only tells you you are charging at 44W gets to me too.

**Comment by TrystanLea** [comment]
Thanks @iz4c 

Could you include a screenshot of what this looks like? 

I think the intention of the current design of the app is that the charging feed is the net charging rate and the discharge feed is the net discharge rate. The battery itself should not be simultaneously charging and discharging?

**Comment by jernaug** [comment]
﻿
Hi Trystan,

I’ve attached a screenshot below.. I currently have a 10kWh battery built from recycled laptop cells and using the DIYBMS to monitor the 14 x 100 cell packs.
The charging is done via an Eltek Flatpack rectifier that I control via canbus so I can throttle the current depending on the surplus reported by my EmonTX. I have to supply a charging current even when the grid tie inverter (Chinese £200 unit with built in limiting function) is supplying power as the reverse flow into the rectifier will damage it (I know this having blown one already).
The previous version of the code only reported charging current even if discharging at a far greater level. The new version reports the net charge / discharge.

In addition monitoring both charge and discharge rather than an overall net figure is essential for calculating the round trip efficiency of converting AC to DC, storing it in the battery then returning it back to the house via the inverter.
Currently I’m achieving around 76-80%.

The battery time left reporting is also really useful. This is something I think Victron have with their battery monitor systems.

Regards,

Keith

**Comment by jernaug** [comment]
6813B891-1082-4DF0-B769-397ECFEE146C

**Comment by TrystanLea** [comment]
Thanks @jernaug sorry for the delay in merging this

**Pull request merged**
