### PR TITLE
Fix NaNs if solar is 0

### LINKED ISSUE #14: NaN% displayed if no export occurs
In the Solar app, if no export occurs within the selected time-frame, instead of displaying '0%', the app displays 'NaN%'.

Paul

export

### PR DESCRIPTION
**Pull request by mattjgalloway**
Fixes #14.

/cc @Paul-Reed

### CODE REVIEW

**Comment by Paul-Reed** [comment]
@mattjgalloway just applied your diff and I'm seeing --% shouldn't it be 0%

zero

**Comment by mattjgalloway** [comment]
I decided on -- %, because it sort of doesn't make sense to be 0% (which is why it's coming out as NaN) as it's 0/0. Is that 0? Is it infinity? I liked the "-- %" because I trained myself to look at those numbers and see 0% export as "awesome!" and 0% direct as "oh that's terrible". So the "-- %" made me realise that I should ignore these numbers as there's no generation.

**Comment by Paul-Reed** [comment]
Technically, yes you are correct, but I wonder if the end user would expect to see 0% ?
I'll stick a post in the forum and try to get a consensus opinion.

**Comment by mattjgalloway** [comment]
Sure - yeh let's see what others think. I think it's definitely worth distinguishing it from actually 0% somehow. It could be we dim it out for example?

**Comment by Paul-Reed** [comment]
Thanks Matt, added as --%

**Comment by glynhudson** [comment]
Great, sounds good to me. Thanks!

- sent from my mobile device

**Pull request merged**
