### PR TITLE
mysolarpvdivert.php updates to show corrected measures

### PR DESCRIPTION
**Pull request by CDuffers**
mysolarpvdivert.php updated to:
Show the "Balance" unit as "kWh"
For other values change display to kW when >=1000

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks! :+1: 

Would it be possible to include a screen grab illustrating the changes in action? This will help our team review the changes as efficiently as possible. 

Thanks

**Comment by CDuffers** [comment]
Sure, no probs. I'm interested in making things easier for anyone involved
I've changed the tooltip from this:
image


To this:
image

**Comment by Paul-Reed** [comment]
Thanks Clive, I saw your screenshot in the forum, and tested it here.
Thanks for the PR!

Paul

**Comment by glynhudson** [comment]
Great, thanks :+1:

**Pull request merged**
