### PR TITLE
Modular app structure and clean up

### PR DESCRIPTION
**Pull request by adminde**
Hi guys,

as discussed in #48, I just started cleaning up the app module to be more consistend with emoncms naming and structure conventions.
Main change is the addition of a modular structure in Modules/app/Apps to support e.g. softlinking of custom apps to the directory.
~~~
--app
  |--Apps
  |  |--OpenEnergyMonitor
  |  |  |--myelectric
  |  |    |--app.json
  |  |    |--myelectric.php
  |  |  |--mysolarpv
  |  |    |--app.json
  |  |    |--mysolarpv.php
~~~

A new `app_settings.php` file may be optionally created to whitelist apps by their name and change the *app/Apps/* dir.  
As a bonus, I noticed that newly created apps were not opened directly in config mode, hence I added that.

All credits to @pb66 and @greeebs for the original idea and first implementation of a modular structure.  
Most changes were Renames so I'm pretty confident this will work without any unexpected bugs ;)

### CODE REVIEW

**Comment by TrystanLea** [comment]
Thanks @adminde 

Testing here I have come across the following error, I think it might be a simple case issue?


Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(Modules/app/Apps/): failed to open dir: No such file or directory' in /var/www/emoncms/Modules/app/app_model.php:37 Stack trace: #0 /var/www/emoncms/Modules/app/app_model.php(37): RecursiveDirectoryIterator->__construct('Modules/app/App...') #1 /var/www/emoncms/Modules/app/app_controller.php(24): AppConfig->get_available() #2 /var/www/emoncms/core.php(64): app_controller() #3 /var/www/emoncms/index.php(189): controller('app') #4 {main} thrown in /var/www/emoncms/Modules/app/app_model.php on line 37

**Comment by adminde** [comment]
Well that was incredibly stupid 😉 
I accidently used `usort` for the associative array of available apps, effectivly removing all app ids. Sorry about that

**Comment by adminde** [comment]
And I realised that renaming the *Modules/app/apps* dir to an uppercase *Apps* was incredibly stupid as well.
Now everything should work as indented. Sorry again.

**Comment by TrystanLea** [comment]
Thanks @adminde sorry for the delay. Testing again here I get the error "ReferenceError: config is not defined" on line 274 of view: 

    config.app = {
        "use":

**Comment by adminde** [comment]
Well, that one was exactly the same problem as the last one... git does not automatically rename dirs for changed capitalization.
I changed that now for the *Lib* dir... very annoying... I felt so confident about these changes but without cloning the repo from scratch I would've never even noticed this^^

btw, @TrystanLea what would be your opinion regarding the consistent naming scheme for some of the directories as discussed in #48 ? *Lib* and *Views* always Uppercase as done in most other modules?

and as a big fan of this work, I'm always happy to contribute 😉

**Comment by TrystanLea** [comment]
Great @adminde that all works! :)

**Comment by TrystanLea** [comment]
> btw, @TrystanLea what would be your opinion regarding the consistent naming scheme for some of the directories as discussed in #48 ? Lib and Views always Uppercase as done in most other modules?

I dont really have a strong opinion on this one, I should probably have used lower case throughout early on...

**Pull request merged**
