### PR TITLE
Objectoriented data series and feedin app

### PR DESCRIPTION
**Pull request by adminde**
Hi guys,

I wanted to commit some hopefully useful things that come in a bundle with other pull requests I'm creating right now, hence I summarized some things in a [forum thread](https://community.openenergymonitor.org/t/isc-konstanz-summer-contributions/)

This pull-requests includes a new **feedin** app, that primarily caters to the needs of german [EEG](https://en.wikipedia.org/wiki/German_Renewable_Energy_Sources_Act) feed-in tariffs.

emoncms-app-blue 

But doing so, I added some new object oriented graph and data cache functionalities that try to be fast and resource efficient.
- `Modules/app/Lib/feed.js` is now a class that holds the apikey and provides async calls for all api paths.
- `Modules/app/Lib/data.js` provides a cache for requested feed data and allows the aggregated iteration of several feeds at once. It also allows and aggregates the values of unevenly spaced engines like PHPTIMESERIES.
- `Modules/app/Lib/graph.js` is the complete graph shown in the images above and could be used and enhanced in other apps.

The feed selection in the configuration view now also groups feeds by tags - and hence allows the existence of several feeds with the same name but different tags.

`light.js` now also includes a light-colored configuration UI. Any app that includes the light style sheet hence will be shown with a less dark config:

emoncms-app-config|690x338

### CODE REVIEW

**Comment by TrystanLea** [comment]
Hello @adminde 

Sorry for the delay, Im getting some strange behaviour on the My Electric 2 and Octopus app:

image

This is the result from selecting a standard PHPFina cumulative kWh feed.

**Comment by TrystanLea** [comment]
This is what the same view should look like:

image

**Comment by TrystanLea** [comment]
I've made a start by copying over your feed selection code specifically, which appears to be working great! so thankyou!

I think the next step would be to merge just the css changes - before then looking at the feed.js changes.

**Comment by adminde** [comment]
As for all my other pull requests: sorry for this very long delay...

I reduced the complexity for this PR now by hopefully a lot. The changes in feed.js were completely reverted. I'd be flabbergasted if the issues above would still exist :)
The only changes in other apps are now related to the config view. More specifically the new config style depending of the imported light.css or dark.css.

**Comment by TrystanLea** [comment]
Hello @adminde 

I've done a partial merge of your pull request, unfortunately it seems that its now created a lot of conflicts rather than simplifying the comparison of what is left. Would you be able to merge in the master changes and re apply your changes outlined in the git conflict statements? 

Not sure if there's an easier way to do this?

All the best

Trystan

**Comment by TrystanLea** [comment]
A note for reference, this pull request cannot be merged as there are too many changes in a single pull request and what I believe are non-optional colour scheme changes. I will be reviewing the colour schemes, css and standard layouts as part of the work here https://github.com/emoncms/emoncms/issues/1661 and will try to include an option to replicate the suggestions in this pull request for those that would like to use e.g the lighter sidebar.

Im leaving this pull request open for future development reference, with the intention of integrating selectively some of the ideas.
I like the idea of the changes proposed in feed, data and graph.js but need to consider each of these carefully on their own rather than merge the whole lot without an in-depth understanding of the changes. If its possible to break these out into separate pull requests made from a number of different feature branches that might be a better way to review these changes. Sorry that this has been left open and in limbo for so long and thankyou @adminde for trying to make the contribution.

**Pull request closed without merging**
