### PR TITLE
Fixed hardcoded $ signs, added check for blank public holidays value

### PR DESCRIPTION
**Pull request by greeebs**
Fixed hardcoded $ signs, added check for blank public holidays value

### CODE REVIEW

**Comment by greeebs** [comment]
Ah, I see @TrystanLea already pushed a commit with the public holiday fix...

**Comment by Paul-Reed** [comment]
OK to close @greeebs ?

**Comment by greeebs** [comment]
It also fixes a number of hardcoded $ signs... I'll take a look at how @TrystanLea did the PH fix and resubmit this one so it can merge cleanly.

**Comment by Paul-Reed** [comment]
Thanks

**Pull request closed without merging**
