### PR TITLE
Add extra check for empty data

### PR DESCRIPTION
**Pull request by thedumbterminal**
This occurs when connection to the server breaks

Resolves issue: https://github.com/emoncms/app/issues/102

### CODE REVIEW

**Comment by thedumbterminal** [comment]
I've added info to recreate this in the linked issue.

**Comment by thedumbterminal** [comment]
Can this be merged?

**Comment by emrysr** [comment]
hi @thedumbterminal, yes this can be merged - I have emailed the admin that can do this merge, he's out of the office till next week

**Comment by thedumbterminal** [comment]
Thanks for the update

**Comment by TrystanLea** [comment]
Thanks @thedumbterminal

**Pull request merged**
